# Generated by Django 5.1.6 on 2025-03-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('genre', models.CharField(max_length=50)),
                ('synopsis', models.TextField(default='Nothing yet, Sorry.')),
                ('esrb_rating', models.CharField(blank=True, choices=[('E', 'Everyone'), ('E10', 'Everyone 10+'), ('T', 'Teen'), ('M', 'Mature 17+'), ('A', 'Adult Only 18+'), ('RP', 'Rating Pending'), ('RPM', 'Rating Pending Likely Mature 17+'), ('O', 'Other')], max_length=10, null=True)),
                ('developer', models.CharField(max_length=25)),
                ('publisher', models.CharField(max_length=25)),
                ('platform', models.CharField(blank=True, choices=[('P', 'Playstation'), ('X', 'Xbox'), ('S', 'Switch'), ('PC', 'PC'), ('O', 'Other')], max_length=20, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('game_cover_image', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
    ]
