# Generated by Django 5.1.6 on 2025-03-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0002_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='game',
            name='esrb_rating',
            field=models.CharField(blank=True, choices=[('E', 'Everyone'), ('E10', 'Everyone 10+'), ('T', 'Teen'), ('M', 'Mature 17+'), ('A', 'Adult Only 18+'), ('RP', 'Rating Pending'), ('RPM', 'Rating Pending Likely Mature 17+'), ('O', 'Other')], default='O', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(blank=True, choices=[('P', 'Playstation'), ('X', 'Xbox'), ('S', 'Switch'), ('PC', 'PC'), ('O', 'Other')], default='O', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='game',
            name='synopsis',
            field=models.TextField(blank=True, default='Nothing yet, Sorry.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=15),
        ),
    ]
