# Generated by Django 5.1.6 on 2025-03-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0003_alter_game_developer_alter_game_esrb_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.AddField(
            model_name='game',
            name='other',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='pc',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='playstation',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='switch',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='xbox',
            field=models.BooleanField(null=True),
        ),
    ]
