# Generated by Django 5.1.6 on 2025-03-15 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0005_alter_game_developer_alter_game_publisher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='switch',
            new_name='nintendo',
        ),
    ]
