# Generated by Django 5.1.6 on 2025-03-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0006_rename_switch_game_nintendo'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
