# Generated by Django 5.1.6 on 2025-03-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0009_alter_game_slug_review_usersgamesstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersgamesstat',
            name='achievement_count',
            field=models.IntegerField(default=0),
        ),
    ]
