# Generated by Django 5.1.6 on 2025-03-21 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0010_alter_usersgamesstat_achievement_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersgamesstat',
            name='completion',
        ),
    ]
