# Generated by Django 5.1.6 on 2025-03-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0017_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_cover_image',
            field=models.ImageField(blank=True, default='fallback.png', upload_to='game_cover/'),
        ),
    ]
