# Generated by Django 5.1.6 on 2025-04-01 18:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0018_alter_game_game_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
