# Generated by Django 5.1.6 on 2025-04-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0019_postcomment_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Art', 'Art'), ('Img', 'Image'), ('Dis', 'Discussion'), ('Evt', 'Event'), ('Gui', 'Guide'), ('Ann', 'Announcement'), ('Hel', 'Help'), ('O', 'Other')], default='O', max_length=10),
        ),
    ]
